name: Docker Image

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 1,3,5,7'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_SLUG: docker.io/yucatovo/derper
      GHCR_SLUG: ghcr.io/yucat-ovo/derper

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest tailscale version
        run: |
          TAILSCALE_VERSION=$(curl -s https://api.github.com/repos/tailscale/tailscale/releases/latest | jq -r '.tag_name')
          echo "Latest tailscale version: $TAILSCALE_VERSION"
          echo TAILSCALE_VERSION=$TAILSCALE_VERSION >> $GITHUB_ENV

      - name: Check if the image exists
        run: |
          GHCR_TOKEN=$(echo ${{ secrets.GITHUB_TOKEN }} | base64)
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: Bearer $GHCR_TOKEN" \
            https://ghcr.io/v2/${{ github.repository }}/manifests/${{ env.TAILSCALE_VERSION }}
            )
          IMAGE_EXISTS=$(if [ $HTTP_CODE -eq 200 ]; then echo "true"; else echo "false"; fi)
          echo "HTTP code: $HTTP_CODE, Image exists: $IMAGE_EXISTS"
          echo IMAGE_EXISTS=$IMAGE_EXISTS >> $GITHUB_ENV

      - name: Set up QEMU
        if: ${{ env.IMAGE_EXISTS == 'false' || github.event_name != 'schedule' }}
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: ${{ env.IMAGE_EXISTS == 'false' || github.event_name != 'schedule' }}
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        if: ${{ env.IMAGE_EXISTS == 'false' || github.event_name != 'schedule' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ${{ env.DOCKERHUB_SLUG }}:${{ env.TAILSCALE_VERSION }}
            ${{ env.DOCKERHUB_SLUG }}:latest
            ${{ env.DOCKERHUB_SLUG }}:${{ github.sha }}
            ${{ env.GHCR_SLUG }}:${{ env.TAILSCALE_VERSION }}
            ${{ env.GHCR_SLUG }}:latest
            ${{ env.GHCR_SLUG }}:${{ github.sha }}
          build-args: |
            DERP_VERSION=${{ env.TAILSCALE_VERSION }}
